### PR TITLE
Text summerizes

### LINKED ISSUE #20: Text Summarization Tool
Build a text summarization tool that summarizes long articles or documents. Contributors can enhance the summarization algorithms or add support for multiple languages.

### PR DESCRIPTION
**Pull request by daemonX10**
# Description

Data Ingestion Stage: Ingests and prepares data for training.
Data Validation Stage: Validates the ingested data.
Data Transformation Stage: Transforms data, typically involving preprocessing.
Model Trainer Stage: Trains a machine learning model.
Model Evaluation Stage: Evaluates the trained model.

Fixes #20 

## Type of change
- [x] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MrLEGENDx10** [comment]
@prodigyinfotech  , now it is default format . check and response asap.

**Comment by prodigyinfotech** [comment]
Use spaces instead of dash in folder name

**Comment by MrLEGENDx10** [comment]
@prodigyinfotech  check now , updated name

**Comment by MrLEGENDx10** [comment]
@prodigyinfotech

**Comment by prodigyinfotech** [comment]
This is a first and final warning. Respect other's time and stop spamming by tagging us.
We will review as we get time.

**Comment by prodigyinfotech** [comment]
Get yourself issue assigned by commenting on the issue

**Comment by MrLEGENDx10** [comment]
> This is a first and final warning. Respect other's time and stop spamming by tagging us. We will review as we get time.
I apologize for any inconvenience caused and will be more mindful of our conduct. My enthusiasm to contribute to the open-source community got the better of me, and as a newcomer, I yearn for guidance and validation. Your insights and expertise are invaluable to me, and I eagerly await your feedback to rectify any missteps promptly.
Thank you for your understanding and patience.

**Comment by MrLEGENDx10** [comment]
> Get yourself issue assigned by commenting on the issue

I kindly request your thorough review and validation of my pull request (PR). If you find it to meet the required standards and align with the project's objectives, I respectfully request your consideration for merging. If it fails, please assign me. 
Thank you for your time and attention to this matter.

**Comment by prodigyinfotech** [comment]
Hey @MrLEGENDx10,

As stated, go to the Issue and comment and comment that you would like to work on it.
After that, it will be assigned to you and then this PR will be merged

**Pull request merged**
