### PR TITLE
Car price prediction model

### LINKED ISSUE #18: Car Price Prediction
Build a model to predict the price of used cars based on features like mileage, brand, year, and model.

### PR DESCRIPTION
**Pull request by daemonX10**
# Description

Using the Application
Access the application in your web browser by navigating to http://localhost:5000 (or the port specified when running the app).

You will be presented with a web form to input information about the car you want to predict the price for. Fill in the details, including the year, present price, kilometers driven, owner count, fuel type, seller type, and transmission type.

Click the "Predict" button.

The application will use the trained model to make a prediction based on your input and display the estimated selling price.

Project Structure
app.py: The main Python file that defines the Flask web application.
random_forest_regression_model.pkl: The trained machine learning model for car price prediction.
templates/index.html: The HTML template for the web page.
static/style.css: A CSS file for styling the web page.

## Issue
Fixes #18  car price prediction

## Type of change

- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by MrLEGENDx10** [comment]
@prodigyinfotech check, feedback and marge with "hacktoberfest-accepted" label.

**Comment by MrLEGENDx10** [comment]
#18

**Comment by prodigyinfotech** [comment]
Multiple Projects in single PR. Fix it

**Comment by MrLEGENDx10** [comment]
Ok

**Comment by MrLEGENDx10** [comment]
> Multiple Projects in single PR. Fix it
check now , response ASAP .

**Comment by prodigyinfotech** [comment]
Use spaces instead of dash in folder name

**Comment by MrLEGENDx10** [comment]
name being updated , dash to space . 
check it out @prodigyinfotech

**Comment by MrLEGENDx10** [comment]
@MrLEGENDx10

**Comment by MrLEGENDx10** [comment]
@prodigyinfotech

**Pull request merged**
