### PR TITLE
Plant Species Identification

### LINKED ISSUE #54: Plant Species Identification
Build a model that uses machine learning algorithms to correctly identify the plant species through the binary leaf images and evaluated features. These features include shape, margin, and texture.

### PR DESCRIPTION
**Pull request by ahaandesai27**
# Description
We have used transfer learning and trained mobile net V2 to identify binary leaf images. The model has been trained to an accuracy of 97% on the train set.
Note that we were not able to calculate the test accuracy as the test dataset did not include the labels.
## Issue
Fixes #54

## Type of change
- [x] New Project

# Checklist:

- [x] I have included a README file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Please add link to dataset in your README.md file and remove the dataset from the PR

**Comment by ahaandesai27** [comment]
Done

**Comment by prodigyinfotech** [comment]
Please add some SS of the results in README file

**Comment by ahaandesai27** [comment]
Will do

**Pull request merged**
