### PR TITLE
PR : Diabetes Prediction

### LINKED ISSUE #17: Predicting Diabetes
Create a model to predict the likelihood of a person developing diabetes based on health-related features like BMI, age, and blood pressure.

### PR DESCRIPTION
**Pull request by prathimacode-hub**
# Description

I had worked on Diabetes Prediction issue that predicts whether a person has diabetes or not. This prediction will help one gets aware of it, as it's the common risk that many people face these days due to sedentary lifestyle.

Kindly review the PR and add the hacktoberfest label to it. Thank You.

## Issue

Fixes #17  

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a REAME file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
@prodigyinfotech, Can you review and merge the PR? Thank You.

**Comment by prodigyinfotech** [comment]
Good work! Merging

**Comment by prathimacode-hub** [comment]
> Good work! Merging

Thank you. @prodigyinfotech

**Comment by prathimacode-hub** [comment]
Can you add the "hacktoberfest-accepted" label to this PR? It isn't showing in Hacktoberfest Contributions.

**Comment by prathimacode-hub** [comment]
> Good work! Merging

Thank you. @prodigyinfotech

**Pull request merged**
