### PR TITLE
Added Sentiment analysis for text

### LINKED ISSUE #11: Sentiment Analysis for Text
Develop a sentiment analysis model that can classify text as positive, negative, or neutral. You can start with movie reviews or social media comments datasets.

### PR DESCRIPTION
**Pull request by Rc17git**
# Description

I have responded to issue #11 (sentiment analysis for text) and added a folder in accordance with git hub's contribution guidelines, which includes '.ipynb' which explains the entire procedure for developing a sentiment analysis model that can classify text as positive, negative, or neutral. I have used Twitter dataset (source mentioned in the file itself)

Fixes #11 

# Checklist:
- [ done] My code follows the style guidelines of this project
- [done ] I have performed a self-review of my code
- [done ] I have provided markdowns in my code, particularly in hard-to-understand areas 
- [done ] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Rc17git** [comment]
Hi @prodigyinfotech  can you review this PR?

**Comment by prodigyinfotech** [comment]
Remove DS Store, Add README, Add Screenshot

**Comment by Rc17git** [comment]
Hey @prodigyinfotech can you check the updated PR?

**Comment by prodigyinfotech** [comment]
Remove .DS Store file

**Comment by Rc17git** [comment]
Done!!

**Pull request merged**
