### PR TITLE
Principal Component Analysis

### LINKED ISSUE #48: 🚀 Project: PCA(Principal Component Analysis) for beginners
### 🔖 Project description

The project helps in familiarization with PCA, one of the easiest and most important things in ML with proper documentation and story telling.

### 🎤 Pitch

This will help new persons to get started with ML. Learn more about various algorithms and PCA is used for feature extraction. So they can be important. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/Prodigy-InfoTech/.github/blob/main/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by Avishek8136**
# Description

The work is a PCA fully documented page for beginners. The work lets beginners learn about the curse of dimensionality and how to tackle it in a storytelling way.

## Issue

Fixes #48 

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a README file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
fix your markdown

**Comment by Avishek8136** [comment]
I didn't get it sir
Can you explain what all changes should I make

**Comment by prodigyinfotech** [comment]
To tick a box you need to use `[x]` and not use tick emoji,

**Comment by Avishek8136** [comment]
Sorry Done.

**Pull request merged**
