### PR TITLE
Added Spam email classifier

### LINKED ISSUE #13: Spam Email Classifier
Build a spam email classifier to detect whether an incoming email is spam or not. Use a dataset of labelled emails for training.

### PR DESCRIPTION
**Pull request by Rc17git**
# Description

I have responded to issue #13  (sentiment analysis for text) and added a folder in accordance with git hub's contribution guidelines, which includes '.ipynb' which explains the entire procedure for developing an E-mail Classification model that can classify an E-mail as Spam or not Spam. I have used a labeled dataset (source mentioned in the file itself)

## Issue

Fixes #13 

## Type of change
- [ ] Bug fix
- [X] New Project

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have provided markdowns in my code, particularly in hard-to-understand areas
- [X] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Remove other files ad drop the .DS_store files

**Comment by Rc17git** [comment]
> Remove other files ad drop the .DS_store files

I have made the requested changes.

**Comment by prodigyinfotech** [comment]
Hey. You are dropping the existing files in the repository.
You dont need to that as part of your commit. Just add your folder as per of your commit.

**Comment by Rc17git** [comment]
> Hey. You are dropping the existing files in the repository.
> You dont need to that as part of your commit. Just add your folder as per of your commit.

So I have to keep the existing files of the repository and my added folder in the commit right?

**Comment by prodigyinfotech** [comment]
Yes

**Comment by Rc17git** [comment]
> Yes

Hi! kindly check the updated PR.

**Comment by prodigyinfotech** [comment]
Remove the .DS Store file and Add a readme file

**Pull request merged**
