### PR TITLE
Stock Price Predictor

### LINKED ISSUE #49: Stock Prices Predictor
Build a system that learns about a company's performance and predicts future stock prices.

### PR DESCRIPTION
**Pull request by Avishek8136**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Issue

Fixes #49 

## Type of change
- [ ] Bug fix
- [x] New Project

# Checklist:

- [x] I have included a README file for my Project (not for Bug fix)
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas 
- [x] I have followed the [Contributing Guidelines](https://github.com/Prodigy-InfoTech/.github/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by prodigyinfotech** [comment]
Add screenshot of the Results

**Comment by Avishek8136** [comment]
> Add screenshot of the Results

Sure
I will do it by Evening.

**Comment by Avishek8136** [comment]
Done

**Comment by Avishek8136** [comment]
Sorry for being late

**Review by Avishek8136 — COMMENTED** [review]
The images are added with various visualizations

**Pull request merged**
